name: col action

on:
  schedule:
    - cron: '30 */6 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "tf1 bot"
      
      - name: updating cstar
        run: sh ${GITHUB_WORKSPACE}/parser/cstar.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "cstar updated"
          git push
