name: w9 action

on:
  schedule:
    - cron: '0 */4 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "w9 bot"
      
      - name: updating w9
        run: sh ${GITHUB_WORKSPACE}/parser/w9.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "w9 updated"
          git push
